### ISSUE TITLE
More issues:((( may have to drop this addon! KILLING me in raid

### ISSUE THREAD

**Issue by Nymike58** [Kkthnx/KkthnxUI#26] opened 2019-03-05 23:20 UTC
**Description**

**Version Number**

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**

**Actual Behavior**

**Only KkthnxUI Enabled**

**Additional Information**

**Error Log**

```

```

**Comment by Nymike58** [comment] 2019-03-05 23:21
![wowscrnshot_030519_174808](https://user-images.githubusercontent.com/47833527/53844346-6cc2b780-3f73-11e9-8076-360ba87cb659.jpg)
![wowscrnshot_030419_223347](https://user-images.githubusercontent.com/47833527/53844361-751af280-3f73-11e9-8671-1df9f4f4eb60.jpg)
![wowscrnshot_030419_222832](https://user-images.githubusercontent.com/47833527/53844391-89f78600-3f73-11e9-8000-71c2f3cdbbd1.jpg)

**Comment by Kkthnx** [comment] 2019-03-06 01:15
Try the latest GitHub version. We have pushed a lot of fixes.

**Comment by Kkthnx** [comment] 2019-03-06 01:17
Also once you download the latest. See if you can reproduce these with only my UI enabled with no other add-ons

Thank you!

**Comment by Nymike58** [comment] 2019-03-06 04:05
I do all my downloads through Twitch and it says I have the latest version. Now what?

Michael Retto mcr1937@aol.com


-----Original Message-----

**Comment by Kkthnx** [comment] 2019-03-06 05:53
Well, I am asking that you download the latest GitHub version. We have not released it yet because there is still some things to be done before the next release but a lot of this has been smashed. Please take time to manually download the latest GitHub version and use it.

**Comment by Nymike58** [comment] 2019-03-06 22:00
Can you please provide download link or on your site tell me where it is? Ty sorry I'm a noob.

Michael Retto mcr1937@aol.com


-----Original Message-----

**Comment by Kkthnx** [comment] 2019-03-06 22:55
https://github.com/Kkthnx/KkthnxUI/archive/master.zip

**Comment by Nymike58** [comment] 2019-03-07 01:27
Ty so much

Michael Retto mcr1937@aol.com


-----Original Message-----

**Comment by Nymike58** [comment] 2019-03-07 04:42
Ok all seems to be working well except this one error when I get rezzed.
![wowscrnshot_030619_223320](https://user-images.githubusercontent.com/47833527/53932801-70d10100-4069-11e9-80e3-5d7879cca52a.jpg)

**Comment by Kkthnx** [comment] 2019-03-07 07:45
You have mixed files here. This was fixed already. Delete your files of KkthnxUI, KkthnxUI_Config then drag in the new ones. Make sure your games are closed first too. I can tell you have mixed files because of the font and that error.

**Comment by goldpaw** [comment] 2019-03-08 13:27
World of Warcraft only reads the folder trees on startup. This means that if files have been removed, moved, or added in an addon update, you MUST restart the entire game for the changes to take effect without bugs, and not just /reload or log in and out. Full restart.

**Comment by Kkthnx** [comment] 2019-03-09 14:46
I'm going to close this as I can not reproduce this error and the user did not properly fill the required info.

**Closed by Kkthnx** 2019-03-09 14:46 UTC
